---
title: "QC and Cell Type Annotation"
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output: 
  rmdformats::readthedown:
    toc_depth: 2
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,  message=FALSE, warning=FALSE, results = 'hide', fig.width=7, fig.height = 7,tidy = TRUE, tidy.opts = list(comment = FALSE))
```

```{css, echo=FALSE}
#content{
    max-width:1920px;
}
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#load the library and set the parameters and load our own function
library(Seurat)
library(data.table)
library(dplyr)
library(ggplot2)
library(pheatmap)
library(RCurl)
library(knitr)
library(kableExtra)
source("scRNA_func.r")
source("reportFunctions.R")
```

# Files Parameters

```{r, echo=FALSE, results="asis"}
option_table<-read.table("fileList1.txt", sep="\t", stringsAsFactors = F) %>% 
  relocate("V2") %>% 
  dplyr::rename(Value=V1, Parameter=V2)

myoptions<-split(option_table$Value, option_table$Parameter)
detail_folder=paste0(myoptions$prefix, gsub(".html", "", myoptions$rmd_ext))

print(kable(option_table))

obj_map<-read_file_map('fileList2.txt')
samples_names=names(obj_map)

has_signacx<-file.exists('fileList4.txt')
if(has_signacx){
  signacx_map<-read_file_map('fileList4.txt')
}

has_singler<-file.exists('fileList5.txt')
if(has_singler){
  singler_map<-read_file_map('fileList5.txt')
}

has_azimuth<-file.exists('fileList8.txt')
if(has_azimuth){
  azimuth_map<-read_file_map('fileList8.txt')
}
```

# Sample summary

```{r echo=FALSE, results="asis"}
stats_df<-fread(file.path(detail_folder, "sample_summary.csv"), data.table=F)
if(all(is.na(stats_df$cluster_remove))){
  stats_df=stats_df[,colnames(stats_df) != "cluster_remove"]
}
print(kable(stats_df))
```

# Sample/Celltype

```{r echo=FALSE, results="asis"}
ct_tb<-fread(file.path(detail_folder, "sample_celltype.csv"), data.table=F)
colnames(ct_tb)[1] = "sample"
print(kable(ct_tb))
```

<br/>

```{r echo=FALSE}
add_figure=function(result, filepath, filedescription){
  if(file.exists(filepath)) {
    result<-paste0(result, filedescription)
    result<-paste0(result, getFigure(filepath))
  }
  return(result)
}

resFile<-"samples.Rmd"
figureRmd<-function(obj_map, samples_names){
  result<-""
  
  cur_sample=samples_names[1]
  for(cur_sample in samples_names){
    sample_path = obj_map[[cur_sample]]
    sample_prefix=file.path(dirname(sample_path), "details", cur_sample)

    if(!file.exists(paste0(sample_prefix, ".qc1.png"))){
      next
    }
    result<-paste0(result, paste0("\n\n# ", cur_sample, "\n\n"))

    result = add_figure(result, paste0(sample_prefix, ".qc1.png"), "## Violin plot of nGene,nUMI and mtRNA distribution\n\n")
    result = add_figure(result, paste0(sample_prefix, ".qc2.png"), "## The scatterplot between mtRNA/nGene and nUMI\n\n")
    result = add_figure(result, paste0(sample_prefix, ".qc3.png"), "## The density plot between nUMI/nGene and mtRNA \n\n")
    result = add_figure(result, paste0(sample_prefix, ".qc5.png"), "## nUMI, nGene, mtRNA, nGene and cell distribution in each cluster\n\n")
    result = add_figure(result, paste0(sample_prefix, ".qc4.png"), "## mtRNA, nGene, nUMI and PC1 in UMAP\n\n")
    result = add_figure(result, paste0(sample_prefix, ".qc6.png"), "## Cluster in PCA/UMAP\n\n")
    result = add_figure(result, paste0(sample_prefix, ".celltype.png"), "## Cell type annotation\n\n")
    result = add_figure(result, paste0(sample_prefix, ".qc7.png"), "## Cell type cluster annotation\n\n")
    result = add_figure(result, file.path(detail_folder, paste0(cur_sample, ".decontX.png")), "## DecontX\n\n")
    result = add_figure(result, paste0(sample_prefix, ".cta.png"), "\n## Cell type annotation score\n\n")
    result = add_figure(result, paste0(sample_prefix, ".heatmap.png"), "\n## Heatmap of highly expressed gene of each cluster\n\n")
    result = add_figure(result, paste0(sample_prefix, ".bubble.png"), "\n## Expression of user defined marker genes\n\n")

    if(has_signacx){
      result = add_figure(result, gsub(".meta.rds", ".SignacX.dot.png", signacx_map[[cur_sample]]), "\n### SignacX: Cell types > 1%\n\n")
    }

    if(has_singler){
      result = add_figure(result, gsub(".meta.rds", ".SingleR.dot.png", singler_map[[cur_sample]]), "\n### SingleR: Cell types > 1%\n\n")
    }

    if(has_azimuth){
      result = add_figure(result, gsub(".meta.rds", ".Azimuth.dot.png", azimuth_map[[cur_sample]]), "\n### Azimuth: Cell types > 1%\n\n")
    }

    result = add_figure(result, paste0(sample_prefix, ".validation.png"), paste0("\n## Validation of", cur_sample, "\n\n"))

    result<-paste0(result, "\n---\n")
  }
  return(result)
}
cat(figureRmd(obj_map, samples_names), file=resFile)

```

```{r, child=resFile} 
```
