---
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmdformats::readthedown:
    toc_depth: 3
    code_folding: hide
    number_sections: yes
---

```{css, echo=FALSE}
#content{
    max-width:1920px;
}
```

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)

knitr::opts_chunk$set(
  echo=TRUE, 
  include=TRUE, 
  warning=FALSE, 
  message=FALSE, 
  results="asis"
)
```

```{r}
source('reportFunctions.R')
source('scRNA_func.r')

pairs = fread("fileList1.milo.txt", header=FALSE, data.table=FALSE)
comparisons = unique(pairs$V3)

myoptions_tbl = fread("fileList2.milo.txt", header=FALSE, data.table=FALSE) |> 
  dplyr::rename(Value=1, Variable=2) |>
  dplyr::select(Variable, Value)
  
print_table(myoptions_tbl, row.names=FALSE)
  
myoptions = split(myoptions_tbl$Value, myoptions_tbl$Variable)

task_name = get_option_value(myoptions, "task_name", required=TRUE)
ct = get_option_value(myoptions, "celltype", required=TRUE)
annotation_column=get_option_value(myoptions, "annotation_column", required=FALSE)
SpatialFDR = as.numeric(get_option_value(myoptions, "SpatialFDR", required=FALSE, default=0.1))
optimized_neighbour_cells = as.numeric(get_option_value(myoptions, "optimized_neighbour_cells", required=TRUE))
```

---
title: "milo report of `r ct` of  `r task_name`"
---

```{r}
neighbourhoods_files = read_file_map("fileList3.milo.txt", do_unlist=FALSE)
miloR_files = read_file_map("fileList4.milo.txt", do_unlist=FALSE)
miloDE_files = read_file_map("fileList5.milo.txt", do_unlist=FALSE)
```

```{r}
sub_content=""
for (comparison in comparisons) {
  sub_content = paste0(sub_content, "```{r}\ncomparison=\"", comparison, "\"\n```\n")
  sub_content = paste0(sub_content, "\n```{r child='milo_report_sub.rmd'}\n")
  sub_content = paste0(sub_content, "```\n\n")
}
sub_rmd="comparison.rmd"
writeLines(sub_content, sub_rmd)
```

```{r child=sub_rmd}
```

# Save the session information

```{r}
writeLines(capture.output(sessionInfo()), paste0(task_name, '.sessionInfo.txt'))
```
