---
title: "Dynamic cell type validation"
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output: 
  rmdformats::readthedown:
    toc_depth: 3
    number_sections: true
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo=FALSE,  
                      message=FALSE, 
                      warning=FALSE, 
                      results = 'asis', 
                      fig.width=7, 
                      fig.height = 7,
                      tidy = TRUE, 
                      tidy.opts = list(comment = FALSE))
```

```{css, echo=FALSE}
#content{
    max-width:1920px;
}
```

```{r data, echo = FALSE}
source("reportFunctions.R")
source("scRNA_func.r")
library(kableExtra)

option_table<-read.table("fileList1.txt", sep="\t", stringsAsFactors = F) %>% 
  relocate("V2") %>% 
  dplyr::rename(Value=V1, Parameter=V2)

myoptions<-split(option_table$Value, option_table$Parameter)

print_table(option_table, row.names=F)
```

```{r, echo = FALSE}
outFile=myoptions$task_name
celltype_column=myoptions$celltype_column

detail_prefix=file.path(paste0(outFile, gsub(".html","",myoptions$rmd_ext)), outFile)

if(file.exists("iter_png.txt")){
  iter_png_file=unlist(readLines("iter_png.txt"))
  if(!file.exists(iter_png_file)){
    stop(paste0("Cannot find file:", iter_png_file))
  }

  iter_png<-read.csv(iter_png_file)
}else{
  iter_png = NULL
}

meta_file=paste0(detail_prefix, ".meta.rds")
if(!file.exists(meta_file)){
  stop(paste0("Cannot find file ", meta_file))
}
meta<-readRDS(meta_file)

cts<-levels(meta[,celltype_column])
if(all(is.null(cts))){
  tb<-table(meta[,celltype_column])
  tb<-tb[order(tb, decreasing = TRUE)]
  cts<-names(tb)
}

get_last_figure<-function(ct_png, png_type){
  type_png_list<-ct_png[ct_png$type == png_type, "fname"]
  return(type_png_list[length(type_png_list)])
}

resFile<-"cluster.Rmd"

choose_figure_rmd<-function(detail_prefix, cts){
  result<-""

  ct=cts[1]
  for(ct in cts){
    ct_name = celltype_to_filename(ct)
    ct_png = paste0(detail_prefix, ".", ct_name, ".png")
    result<-paste0(result, paste0("\n\n# ", ct, "\n\n"))
    result<-paste0(result, getFigure(ct_png))
  }
  return(result)
}

iter_figure_rmd<-function(detail_prefix, cts, iter_png){
  result<-""

  ct=cts[1]
  for(ct in cts){
    result<-paste0(result, paste0("\n\n# ", ct, "\n\n"))
    ct_name = celltype_to_filename(ct)

    if(!is.null(iter_png)){
      ct_png<-iter_png[iter_png$pct == ct,]

      old_umap = get_last_figure(ct_png, "old_umap")
      new_umap = get_last_figure(ct_png, "new_umap")
      dot = get_last_figure(ct_png, "dot")
      cta_png = get_last_figure(ct_png, "cta_png")

      singleR_file = paste0(detail_prefix, ".", ct_name, ".SingleR.png")
      if(file.exists(singleR_file)){
        result<-paste0(result, paste0("\n\n## SingleR\n\n"))
        singleR_csv = paste0(detail_prefix, ".", ct_name, ".SingleR.csv")
        result<-paste0(result, getTable(singleR_csv))

        result<-paste0(result, paste0("\n\n### UMAP\n\n"))
        result<-paste0(result, getFigure(singleR_file))

        singleR_bubble_file = paste0(detail_prefix, ".", ct_name, ".SingleR.bubble.png")
        result<-paste0(result, paste0("\n\n### Curated marker genes\n\n"))
        result<-paste0(result, getFigure(singleR_bubble_file))
      }

      signacX_file = paste0(detail_prefix, ".", ct_name, ".SignacX.png")
      if(file.exists(signacX_file)){
        result<-paste0(result, paste0("\n\n## SignacX\n\n"))
        SignacX_csv = paste0(detail_prefix, ".", ct_name, ".SignacX.csv")
        result<-paste0(result, getTable(SignacX_csv))

        result<-paste0(result, paste0("\n\n### UMAP\n\n"))
        result<-paste0(result, getFigure(signacX_file))

        signacX_bubble_file = paste0(detail_prefix, ".", ct_name, ".SignacX.bubble.png")
        result<-paste0(result, paste0("\n\n### Curated marker genes\n\n"))
        result<-paste0(result, getFigure(signacX_bubble_file))
      }

      azimuth_file = paste0(detail_prefix, ".", ct_name, ".Azimuth.png")
      if(file.exists(azimuth_file)){
        result<-paste0(result, paste0("\n\n## Azimuth\n\n"))
        Azimuth_csv = paste0(detail_prefix, ".", ct_name, ".Azimuth.csv")
        result<-paste0(result, getTable(Azimuth_csv))

        result<-paste0(result, paste0("\n\n### UMAP\n\n"))
        result<-paste0(result, getFigure(azimuth_file))

        Azimuth_bubble_file = paste0(detail_prefix, ".", ct_name, ".Azimuth.bubble.png")
        result<-paste0(result, paste0("\n\n### Curated marker genes\n\n"))
        result<-paste0(result, getFigure(Azimuth_bubble_file))
      }

      overlap_csv = paste0(detail_prefix, ".", ct_name, ".SingleR_SignacX.csv")
      if(file.exists(overlap_csv)){
        result<-paste0(result, paste0("\n\n## Overlap between SingleR and SignacX\n\n"))
        result<-paste0(result, getTable(overlap_csv))
      }

      result<-paste0(result, paste0("\n\n## UMAP\n\n"))
      result<-paste0(result, getFigure(old_umap))

      result<-paste0(result, paste0("\n\n## SUB_UMAP\n\n"))
      result<-paste0(result, getFigure(new_umap))

      result<-paste0(result, paste0("\n\n## Marker genes\n\n"))
      result<-paste0(result, getFigure(dot))

      result<-paste0(result, paste0("\n\n## Cell type enrichment score\n\n"))
      result<-paste0(result, getFigure(cta_png))
    }

    decontx_file = paste0(detail_prefix, ".", ct_name, ".decontX.png")
    if(file.exists(decontx_file)){
      result<-paste0(result, paste0("\n\n## Contanimation score by DecontX\n\n"))
      result<-paste0(result, getFigure(decontx_file))
    }

    result<-paste0(result, paste0("\n\n## Validation\n\n"))
    vc_file = paste0(detail_prefix, ".", ct_name, ".png")
    result<-paste0(result, getFigure(vc_file))
  }
  return(result)
}

if(is.null(iter_png)){
  writeLines(choose_figure_rmd(detail_prefix, cts), resFile)
}else{
  writeLines(iter_figure_rmd(detail_prefix, cts, iter_png), resFile)
}
```

```{r, child=resFile} 
```

