---
title: "Marker gene report"
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output: 
  rmdformats::readthedown:
    toc_depth: 3
    number_sections: true
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(kableExtra)
knitr::opts_chunk$set(echo=FALSE,  message=FALSE, warning=FALSE, results = 'asis', fig.width=7, fig.height = 7,tidy = TRUE, tidy.opts = list(comment = FALSE))
```

```{css, echo=FALSE}
#content{
    max-width:1920px;
}
```

```{r data, echo = FALSE}
source("scRNA_func.r")
source("reportFunctions.R")

files<-read.table("fileList1.txt", sep="\t", header=F, stringsAsFactors = F)
categories<-unique(files$V3)

options_table<-read.table("fileList2.txt", sep="\t", header=F, stringsAsFactors = F)
myoptions<-split(options_table$V1, options_table$V2)

outfile<-myoptions$task_name

samples<-readLines(paste0(outfile, ".sample.txt"))
cts<-readLines(paste0(outfile, ".cell_type.txt"))

resFile<-"sub.Rmd"
figureRmd<-function(categories, samples, cts){
  result<-""
  category = categories[1]

  has_multi_cateogries = length(categories) > 1
  has_multi_cell_types = length(cts) > 1
  has_multi_samples = length(samples) > 1
  
  result<-paste0(result, paste0("\n\n# Overview\n\n"))
  for(category in categories){
    if(has_multi_cateogries){
      result<-paste0(result, paste0("\n\n## ", category, "\n\n"))
    }
    result<-paste0(result, getFigure(paste0("details/", outfile, ".", category, ".bubblemap.ct.png")))
  }

  category_ct_cluster_png = paste0("details/", outfile, ".", categories[1], ".bubblemap.ct_cluster.png")
  if(file.exists(category_ct_cluster_png)) {
    result<-paste0(result, paste0("\n\n# Celltype / cluster\n\n"))
  
    ct = cts[1]
    for(ct in cts){
      result<-paste0(result, paste0("\n\n## ", ct, "\n\n"))
      ct_str = celltype_to_filename(ct)
      for(category in categories){
        cur_png=paste0("details/", outfile, ".", category, ".bubblemap.ct_cluster.", ct_str, ".png")
        if(file.exists(cur_png)){
          if(has_multi_cateogries){
            result<-paste0(result, paste0("\n\n### ", category, "\n\n"))
          }
          result<-paste0(result, getFigure())
        }
      }
    }
  }

  if(has_multi_samples) {
    result<-paste0(result, paste0("\n\n# Celltype / sample\n\n"))

    ct = cts[1]
    for(ct in cts){
      result<-paste0(result, paste0("\n\n## ", ct, "\n\n"))
      ct_str = celltype_to_filename(ct)
      for(category in categories){
        cur_png=paste0("details/", outfile, ".", category, ".bubblemap.ct_ident.", ct_str, ".png")
        if(file.exists(cur_png)){
          if(has_multi_cateogries){
            result<-paste0(result, paste0("\n\n### ", category, "\n\n"))
          }
          result<-paste0(result, getFigure(cur_png))
        }
      }
    }

    result<-paste0(result, paste0("\n\n# Sample / celltype\n\n"))
    sample = samples[1]
    for(sample in samples){
      result<-paste0(result, paste0("\n\n## ", sample, "\n\n"))
      for(category in categories){
        cur_png=paste0("details/", outfile, ".", category, ".bubblemap.ident_ct.", sample, ".png")
        if(file.exists(cur_png)){
          if(has_multi_cateogries){
            result<-paste0(result, paste0("\n\n### ", category, "\n\n"))
          }
          result<-paste0(result, getFigure(cur_png))
        }
      }
    }
  }

  return(result)
}
cat(figureRmd(categories, samples, cts), file=resFile)

```

```{r, child=resFile} 
```

