---
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output: 
  rmdformats::readthedown:
    toc_depth: 3
    number_sections: true
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo=FALSE,  
                      message=FALSE, 
                      warning=FALSE, 
                      results = 'asis', 
                      fig.width=7, 
                      fig.height = 7,
                      tidy = TRUE, 
                      tidy.opts = list(comment = FALSE))
```

```{css, echo=FALSE}
#content{
    max-width:1920px;
}
```

```{r data, echo = FALSE}
library('sf')
library(Seurat)
library(data.table)
library(dplyr)
library(ggplot2)

source("reportFunctions.R")
source("scRNA_func.r")

options(future.globals.maxSize = 600000 * 1024^2)
options(future.seed = TRUE)

myoptions<-read_file_map("fileList2.txt", do_unlist=FALSE)
email=myoptions$email
affiliation=get_affiliation(myoptions)
assay=myoptions$assay
species=myoptions$species

resolutions=sort(as.numeric(myoptions$MEcell_resolutions))
resolutions_str=paste0(resolutions, collapse="_")

algorithm_name=myoptions$cluster_algorithm_name

bubblemap_file=myoptions$bubblemap_file
bubblemap_width_in=as.numeric(myoptions$bubblemap_width_in)

file_map<-read_file_map("fileList1.txt", do_unlist=FALSE)
sample_name=names(file_map)[1]
rds_file=file_map[[sample_name]]

cluster_map=read_file_map("fileList3.txt", do_unlist=FALSE)
cluster_files=cluster_map[[sample_name]]

detail_folder="details"
if(!dir.exists(detail_folder)){
  dir.create(detail_folder)
}

```

---
title: "MEcell cluster - `r sample_name`"
author:
- name: `r myoptions$email`
  affiliation: `r myoptions$affiliation`
---

```{r}
ctdef<-init_celltype_markers(panglao5_file = myoptions$markers_file,
                             species = species,
                             curated_markers_file = myoptions$curated_markers_file,
                             HLA_panglao5_file = myoptions$HLA_panglao5_file,
                             layer="Layer4",
                             remove_subtype_str = myoptions$remove_subtype,
                             combined_celltype_file = NULL)

cell_activity_database<-ctdef$cell_activity_database

predict_celltypes<-function(filtered_obj, assay, cluster, cluster_cell_type, cell_activity_database){
  data_norm=get_seurat_average_expression(filtered_obj, cluster, assay=assay)
  
  predict_celltype<-ORA_celltype(data_norm,cell_activity_database$cellType,cell_activity_database$weight)

  new_cluster_ids<-paste0(colnames(data_norm), ": ", names(predict_celltype$max_cta))
  names(new_cluster_ids)<-colnames(data_norm)

  filtered_obj@meta.data[[cluster_cell_type]] = factor_by_count(new_cluster_ids[as.character(filtered_obj@meta.data[[cluster]])])
  return(filtered_obj)
}
```

# Load Seurat object

Load data from `r rds_file` and perform MEcell clustering at resolutions: `r resolutions_str` using algorithm: `r algorithm_name`.

```{r}
if(!file.exists(rds_file)){
  stop(paste0("RDS file not found: ", rds_file))
}

obj = readRDS(rds_file)
obj = UpdateSeuratObject(obj)

bMiss=FALSE
cfile = cluster_files[1]
for(cfile in cluster_files){
  if(!file.exists(cfile)){
    cat(paste0("Warning: Cluster file not found: ", cfile, "\n"))
    bMiss=TRUE
    next
  }

  cmeta = readRDS(cfile)
  stopifnot(all(rownames(cmeta) == rownames(obj@meta.data)))
  cluster_col = grep("MEcell_res.", colnames(cmeta), value=TRUE)
  cur_col=cluster_col[1]
  for(cur_col in cluster_col){
    #somehow, the leiden will generate more than 100 clusters, 
    #and the names are not ordered by number of cells.
    #we need to rename them here.
    cur_tbl=table(cmeta[[cur_col]])
    cur_tbl=cur_tbl[order(-cur_tbl)]
    rename_map = setNames(seq_along(cur_tbl), names(cur_tbl))
    cmeta[[cur_col]] = rename_map[as.character(cmeta[[cur_col]])]
    obj@meta.data[[cur_col]] = factor_by_count(cmeta[[cur_col]])
  }
}
```

```{r}
hasAzimuth=file.exists('fileList4.txt')
if(hasAzimuth){
  azimuth_file_map=read_file_map("fileList4.txt", do_unlist=FALSE)
  azimuth_file=azimuth_file_map[[sample_name]]
  azimuth_meta=readRDS(azimuth_file)
  stopifnot(all(rownames(azimuth_meta) == rownames(obj@meta.data)))
  obj@meta.data[["Azimuth"]] = azimuth_meta$Azimuth_finest
}
```

```{r}
hasRCTD=file.exists('fileList5.txt')
if(hasRCTD){
  rctd_file_map=read_file_map("fileList5.txt", do_unlist=FALSE)
  rctd_file=rctd_file_map[[sample_name]]
  rctd_obj=readRDS(rctd_file)
  stopifnot(all(rownames(rctd_obj@meta.data) == rownames(obj@meta.data)))
  obj@meta.data[["RCTD1"]] = rctd_obj@meta.data[["RCTD1_spot_class"]]
  obj@meta.data[["RCTD1_first_type"]] = rctd_obj@meta.data[["RCTD1_first_type"]]
}
```

```{r}
hasSingleR=file.exists('fileList6.txt')
if(hasSingleR){
  singleR_file_map=read_file_map("fileList6.txt", do_unlist=FALSE)
  singleR_file=singleR_file_map[[sample_name]]
  singleR_meta=readRDS(singleR_file)
  stopifnot(all(rownames(singleR_meta) == rownames(obj@meta.data)))
  obj@meta.data[["SingleR"]] = singleR_meta[["SingleR_major_labels"]]
}
```
```{r}
hasSignacX=file.exists('fileList7.txt')
if(hasSignacX){
  signacX_file_map=read_file_map("fileList7.txt", do_unlist=FALSE)
  signacX_file=signacX_file_map[[sample_name]]
  signacX_meta=readRDS(signacX_file)
  stopifnot(all(rownames(signacX_meta) == rownames(obj@meta.data)))
  obj@meta.data[["SignacX"]] = signacX_meta[["CellStates"]]
}
```

```{r}
hasUMAP=file.exists('fileList8.txt')
if(hasUMAP){
  umap_file_map=read_file_map("fileList8.txt", do_unlist=FALSE)
  umap_file=umap_file_map[[sample_name]]
  umap_results=readRDS(umap_file)
  
  missed_cells=setdiff(rownames(umap_results), rownames(obj@meta.data))
  if(length(missed_cells) > 0) {
    cat("\n\n<mark>There are", length(missed_cells), "cells discarded in UMAP due to number of neighbors limitation. Those cells will not be used in downstream analysis.</mark>\n\n" )
    obj=subset(obj, cells=rownames(umap_results))
  }else{
    stopifnot(all(rownames(umap_results) == rownames(obj@meta.data)))
  }

  obj[["umap"]] <- CreateDimReducObject(
    embeddings = as.matrix(umap_results),
    key = "UMAP_",
    assay = DefaultAssay(obj)
  )
}
```


```{r}
hasImageFeatures=file.exists('fileList9.txt')
if(hasImageFeatures){
  library(arrow)
  
  image_file_map=read_file_map("fileList9.txt", do_unlist=FALSE)
  image_file=image_file_map[[sample_name]]

  obj@meta.data$cell_id=as.numeric(gsub("cellid_", "", gsub("\\-1","",colnames(obj))))

  image_df <- read_parquet(image_file, 
                            col_select = c("cell_id","cell_area_um2","cell_perimeter_um","cell_circularity","nucleus_area_um2","nucleus_perimeter_um","nucleus_circularity")) |>
                            as.data.frame() |>
                            dplyr::mutate(cell_id = as.numeric(cell_id))
  rownames(image_df) <- image_df$cell_id

  stopifnot(all(obj$cell_id %in% image_df$cell_id))

  obj_image_df=image_df[as.character(obj$cell_id), ]
  stopifnot(all(obj$cell_id == obj_image_df$cell_id))

  obj@meta.data = cbind(obj@meta.data, obj_image_df[, -1])
}
```


```{r}
if(!bMiss){
  cat("\n# Save object\n")
  saveRDS(obj, paste0(sample_name, ".", assay, ".MEcell_clustered.rds"))
}
```

```{r}
tissue_image = SpatialPlot( object = obj, 
                            image.alpha = 1, 
                            alpha = c(0, 0)) + 
              ggtitle(paste0("Tissue : ", sample_name)) +
              theme(legend.position = "none",
                    plot.title = element_text(hjust = 0.5),
                    panel.border = element_rect(colour = "black", fill=NA, linewidth=1))
```

```{r}
validation_columns = c()
if(hasRCTD){
  validation_columns = c(validation_columns, "RCTD1", "RCTD1_first_type")
}
if(hasAzimuth){
  validation_columns = c(validation_columns, "Azimuth")
}
if(hasSingleR){
  validation_columns = c(validation_columns, "SingleR")
}
if(hasSignacX){
  validation_columns = c(validation_columns, "SignacX")
}
```

```{r}
cluster_content=""

cur_res=resolutions[1]
for(cur_res in resolutions){
  cluster_content=paste0(cluster_content, "\n# Resolution ", cur_res, "\n\n")
  cluster_col = paste0("MEcell_res.", cur_res)

  if(!(cluster_col %in% colnames(obj@meta.data))){
    # no such cluster column, which means no clustering done at this resolution, ignore
    next
  }

  file_prefix = paste0(detail_folder, "/", sample_name, ".", assay, ".MEcell_res.", cur_res)

  cluster_counts = get_freq_table(obj@meta.data, cluster_col)
  cluster_counts$perc = cluster_counts$count / sum(cluster_counts$count)
  cluster_perc_filtered = cluster_counts |> 
    dplyr::filter(perc >= 0.005) |>
    dplyr::pull(!!sym(cluster_col))

  filtered_obj = subset(obj, subset = !!sym(cluster_col) %in% cluster_perc_filtered)
  filtered_obj@meta.data[[cluster_col]] = factor_by_count(filtered_obj@meta.data[[cluster_col]])

  cluster_cell_type=paste0(cluster_col, "_cell_type")

  filtered_obj = predict_celltypes(filtered_obj, assay, cluster_col, cluster_cell_type, cell_activity_database)

  cluster_cell_type_count_col = paste0(cluster_cell_type, "_count")
  filtered_obj@meta.data = add_column_count(filtered_obj@meta.data, cluster_cell_type, cluster_cell_type_count_col, order_by_count=TRUE)

  cluster_colors = get_colors(current_cell_types=unique(filtered_obj@meta.data[[cluster_cell_type_count_col]]))
  Idents(filtered_obj) <- cluster_cell_type_count_col

  title=paste0(assay, ": MEcell res ", cur_res)

  plots <- list("Tissue Image" = tissue_image)

  plots[['ImageDimPlot']] = get_image_dim_plot( obj=filtered_obj, 
                                                assay=assay, 
                                                group.by=cluster_cell_type_count_col, 
                                                colors=cluster_colors, 
                                                title=title)

  pt.size.factor = ifelse(grepl("Polygons", assay), 0.5, 12)

  plots[['SpatialDimPlot']] = SpatialDimPlot( filtered_obj, 
                                              cols = cluster_colors, 
                                              image.alpha = 0.1,
                                              pt.size.factor = pt.size.factor) + 
    ggtitle(label = title) + 
    theme(plot.title = element_text(hjust = 0.5), 
          panel.border = element_rect(colour = "black", fill=NA, linewidth=1))     


  cluster_png = save_vis_png(plots, file_prefix, cluster_colors, cluster_cell_type_count_col, assay)

  cluster_content=paste0(cluster_content, "\n## Spatial clusters\n\n")
  cluster_content=paste0(cluster_content, getFigure(cluster_png))

  if(hasUMAP) {
    scolors=cluster_colors
    names(scolors)=levels(filtered_obj@meta.data[[cluster_col]])
    g = get_dim_plot(filtered_obj, reduction='umap', group.by=cluster_col, label.by=cluster_cell_type_count_col, scolors=scolors) + 
      ggtitle("UMAP") + theme(plot.title = element_text(hjust = 0.5))
    umap_png = paste0(file_prefix, ".umap.png")    
    width=ifelse(length(cluster_colors) > 17, 12, 9)
    ggsave(umap_png, g, width=width, height=6, units="in", dpi=300, bg="white")
    cluster_content=paste0(cluster_content, "\n## UMAP\n\n")
    cluster_content=paste0(cluster_content, getFigure(umap_png))
  }

  g = ImageDimPlot( object = filtered_obj, 
                    fov = "slice1.polygons", 
                    split.by = cluster_cell_type_count_col,
                    border.size = NA,
                    axes = F, 
                    dark.background = F, 
                    coord.fixed = T) + 
    ggtitle(label = paste0("Resolution : ", cur_res)) + 
    theme(plot.title = element_text(hjust = 0.5), 
          panel.border = element_rect(colour = "black", fill=NA, linewidth=1),
          legend.position = "none",
          strip.background = element_rect(fill="white"))
  g = adjust_ImagePlot_Polygons(g)
  ncol = ifelse(length(cluster_colors) <= 3, length(cluster_colors), ceiling(sqrt(length(cluster_colors))))
  nrow = ceiling(length(cluster_colors) / ncol)
  
  ct_individual_png = paste0(file_prefix, ".ct_individual.png")
  ggsave(ct_individual_png, g, width=ncol * 2.8, height=nrow * 2.8 + 0.3, units="in", dpi=300, bg="white")

  cluster_content=paste0(cluster_content, "\n## Image dim plot of each cluster\n\n")
  cluster_content=paste0(cluster_content, getFigure(ct_individual_png))

  g<-get_bubble_plot( obj = filtered_obj, 
                      group.by = cluster_cell_type_count_col, 
                      bubblemap_file = bubblemap_file, 
                      assay = assay, 
                      orderby_cluster = F,
                      species=species)
  bubblemap_png = paste0(file_prefix, ".dot.png")
  ggsave(bubblemap_png, g, width=bubblemap_width_in, height=max(4, length(cluster_colors) * 0.3 + 2), units="in", dpi=300, bg="white", limitsize = FALSE)

  cluster_content=paste0(cluster_content, "\n## Marker genes\n\n")
  cluster_content=paste0(cluster_content, getFigure(bubblemap_png))

  if(length(validation_columns) > 0){
    bar_file= paste0(file_prefix, ".", assay, ".MEcell_res.", cur_res, ".validation_barplot.png")
    g<-get_barplot( ct_meta=filtered_obj@meta.data, 
                    bar_file=bar_file,
                    cluster_name=cluster_cell_type_count_col, 
                    validation_columns=validation_columns,
                    calc_height_per_cluster=200, 
                    calc_width_per_cell=50)

    cluster_content=paste0(cluster_content, "\n## Validation barplot\n\n")
    cluster_content=paste0(cluster_content, getFigure(bar_file))
  }

  gd = FetchData(filtered_obj, c(cluster_cell_type_count_col, paste0("nCount_", assay)))
  g=ggplot( gd, aes(x=!!sym(cluster_cell_type_count_col), y=!!sym(paste0("nCount_", assay)))) + 
                geom_violin(scale="width") +
                geom_boxplot(width=0.1, outliers=FALSE) +
                theme_classic() +
                theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5),
                      axis.title.x=element_blank())
  vln_png = paste0(file_prefix, ".vln.png")
  ggsave(vln_png, g, width=max(5, length(cluster_colors) * 0.4 + 2), height=4, units="in", dpi=300, bg="white", limitsize = FALSE)

  cluster_content=paste0(cluster_content, "\n## Violin plots of nCount\n\n")
  cluster_content=paste0(cluster_content, getFigure(vln_png))

  if(hasImageFeatures){
    obj_image_df=filtered_obj@meta.data |>
      dplyr::select(cell_id, !!sym(cluster_cell_type_count_col), cell_area_um2, cell_perimeter_um, cell_circularity, nucleus_area_um2, nucleus_perimeter_um, nucleus_circularity) |>
      dplyr::mutate(area_ratio = nucleus_area_um2 / cell_area_um2,
                    perimeter_ratio = nucleus_perimeter_um / cell_perimeter_um ) |>
      tibble::rownames_to_column('cell') |>
      dplyr::rename(Subcluster_count = !!sym(cluster_cell_type_count_col)) |>
      dplyr::select(cell, cell_id, everything())

    melt_df=reshape2::melt(obj_image_df, id.vars=c('cell', 'cell_id', 'Subcluster_count'))
    melt_df$sample=sample_name
    melt_df$variable=factor(melt_df$variable, levels=c("cell_area_um2", "nucleus_area_um2", "cell_perimeter_um", "nucleus_perimeter_um", "cell_circularity", "nucleus_circularity", "area_ratio", "perimeter_ratio"))

    g=ggplot(melt_df, aes(x=Subcluster_count, y=value)) +
      geom_boxplot(outliers=FALSE, width=0.5) +
      facet_wrap(~variable, ncol=2, scales="free_y") +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5),
            plot.title = element_text(hjust = 0.5),
            axis.title.x = element_blank(),
            axis.title.y = element_blank(),
            legend.position="none",
            strip.background = element_blank())

    feature_png = paste0(file_prefix, ".image_features.png")
    ggsave(feature_png, g, width=max(5, length(cluster_colors) * 0.8 + 2), height=8, units="in", dpi=300, bg="white", limitsize = FALSE)

    cluster_content=paste0(cluster_content, "\n## Box plots of image features\n\n")
    cluster_content=paste0(cluster_content, getFigure(feature_png))
  }

  markers_rds = paste0(file_prefix, ".markers.rds")
  if(file.exists(markers_rds)){
    markers = readRDS(markers_rds)
  }else{
    markers = FindAllMarkers( filtered_obj, 
                              assay = assay, 
                              only.pos = TRUE, 
                              min.pct = 0.25, 
                              logfc.threshold = 0.25,
                              group.by = cluster_cell_type_count_col)
    saveRDS(markers, markers_rds)
  }
  if(nrow(markers) == 0){
    cluster_content=paste0(cluster_content, "\n## No marker genes found\n\n")
    next
  }

  top5 = markers |>
    dplyr::filter(p_val_adj < 0.05) |>
    dplyr::mutate(score = avg_log2FC * (pct.1 - pct.2)) |>
    dplyr::group_by(cluster) |>
    dplyr::slice_max(order_by = score, n = 5)

  g = MyDoHeatMap( filtered_obj, 
                  features = top5$gene, 
                  group.by = cluster_col, 
                  assay = assay) 
  heatmap_png = paste0(file_prefix, ".heatmap.png")

  width<-max(6, length(cluster_colors) * 1)
  height<-max(3, length(top5$gene) * 0.2)
  ggsave(heatmap_png, g, width=width, height=height, units="in", dpi=300, bg="white", limitsize = FALSE)

  cluster_content=paste0(cluster_content, "\n## Heatmap of top 5 markers per cluster\n\n")
  cluster_content=paste0(cluster_content, getFigure(heatmap_png))

}

cluster_rmd="cluster.rmd"
writeLines(cluster_content, cluster_rmd)
```

```{r child=cluster_rmd}
```

# Session Info

```{r}
print_table(get_packages_table(), byDT=TRUE, row.names=F)
```
