

pyCloneVIInputListFile=parFile1
pyCloneVIRunFile=paste0(outFile,".runPyCloneVI.sh")

pyCloneVIInputListFileTable=read.delim(pyCloneVIInputListFile,header=T,as.is=T)


###########################################
#Make sh/PBS to run pyCloneVI
###########################################

############################
#test run pyclone
############################
#source activate pyclone-vi
#export PYTHONPATH=""
#pyclone-vi --help
#cd /scratch/cqs/zhaos/workSync/Pierre/20200730_UMI_MuTect2PON_simpleProcessing/sciCloneAllelicCounts/
#pyclone-vi fit -i Tumor_10658_A.Tumor_10658_B.Tumor_10658_C.pyCloneVI.input.txt -o Tumor_10658_A.Tumor_10658_B.Tumor_10658_C.pyCloneVI.input.txt.pyCloneVI.hd5
#pyclone-vi write-results-file -i Tumor_10658_A.Tumor_10658_B.Tumor_10658_C.pyCloneVI.input.txt.pyCloneVI.hd5 -o Tumor_10658_A.Tumor_10658_B.Tumor_10658_C.pyCloneVI.input.txt.pyCloneVI.txt


cloneResultForClonevol=data.frame()
shContents='
source activate pyclone-vi
export PYTHONPATH=""

'

for (i in 1:nrow(pyCloneVIInputListFileTable)) {
  inputPatient=pyCloneVIInputListFileTable[i,1]
  outputName=paste0(inputPatient,".pyCloneVI")
  
  inputFile=pyCloneVIInputListFileTable[i,2]
  outputFileHd5=paste0(outputName,".hd5")
  outputFileTxt=paste0(outputName,".txt")
  pyCloneVICommand=paste0("pyclone-vi fit -i ",inputFile," -o ",outputFileHd5)
  pyCloneVICommand=c(pyCloneVICommand,paste0("pyclone-vi write-results-file -i ",outputFileHd5," -o ",outputFileTxt))
  
  shContents=c(shContents,pyCloneVICommand)
  cloneResultForClonevol=rbind(cloneResultForClonevol,c(inputPatient,paste0(getwd(),"/",outputFileTxt)))

}

writeLines(shContents,pyCloneVIRunFile)
colnames(cloneResultForClonevol)=c("Sample","File")

#should run pyCloneVIRunFile outside R

#check if result is generated by pyCloneVIRunFile
cloneResultForClonevol=cloneResultForClonevol[which(file.exists(cloneResultForClonevol[,2])),]

if (nrow(cloneResultForClonevol)==0) {
  break(paste0("No pyCloneVI results found. Can't run clonevol"))
}


#run clonevol
library(clonevol)
library(tidyr)

for (i in 1:nrow(cloneResultForClonevol)) {
  inputPatient=cloneResultForClonevol[i,1]
  cloneResultFile=sciCloneResultForClonevol[i,2]
  #cloneResultFile="6359.sciClone.txt"
  
  cloneResult=read.delim(cloneResultFile,header=T,as.is=T,check.names=F)
  
  ########################################
  #format pyCloneVI result, export cluster column and vaf column
  ########################################
  
  dataForVis=cloneResult[,c("mutation_id","sample_id","cluster_id","cellular_prevalence")]
  dataForVis$sample_id=gsub("^b'","",dataForVis$sample_id)
  dataForVis$sample_id=gsub("'$","",dataForVis$sample_id)
  clusterCol="cluster_id"
  vafCol=unique(dataForVis$sample_id)
  
  dataForVis=dataForVis %>%  pivot_wider(names_from = c("sample_id"), values_from =c("cellular_prevalence"),id_cols=c("mutation_id","cluster_id"))
  

  dataForVis=dataForVis[which(!is.na(dataForVis[,clusterCol])),]
  dataForVis=dataForVis[order(dataForVis[,clusterCol]),]
  dataForVis$cluster=dataForVis[[clusterCol]]+1 #cluster need start at 1, and only support "cluster" as column name in generate.boot
  clusterCol="cluster"
  
  ########################################
  #run clonevol
  ########################################
  y  = try(infer.clonal.models(
    variants = dataForVis,
    cluster.col.name =clusterCol,
    vaf.col.names = vafCol,
    cancer.initiation.model = 'monoclonal',
    subclonal.test = 'bootstrap',
    subclonal.test.model = 'non-parametric',
    num.boots = 1000,
    founding.cluster = 1,
    cluster.center = 'mean',
    ignore.clusters = NULL,
    min.cluster.vaf = 0.01,
    # min probability that CCF(clone) is non-negative
    sum.p = 0.05,
    # alpha level in confidence interval estimate for CCF(clone)
    alpha = 0.05
  ))
  
  if (class(y)=="try-error" | is.null(y)) {
    print(paste0("clonevol for ",basename(cloneResultFile)," not sucvcessful. Too few command variants between samples?"))
    next
  }
  
  y <- convert.consensus.tree.clone.to.branch(y, branch.scale = 'sqrt')
  
  
  try(
    plot.clonal.models(
      y,
      # box plot parameters
      box.plot = TRUE,
      fancy.boxplot = TRUE,
      #    fancy.variant.boxplot.highlight = 'is.driver',
      #    fancy.variant.boxplot.highlight.shape = 21,
      #    fancy.variant.boxplot.highlight.fill.color = 'red',
      #    fancy.variant.boxplot.highlight.color = 'black',
      #    fancy.variant.boxplot.highlight.note.col.name = 'gene',
      #    fancy.variant.boxplot.highlight.note.color = 'blue',
      #    fancy.variant.boxplot.highlight.note.size = 2,
      fancy.variant.boxplot.jitter.alpha = 1,
      fancy.variant.boxplot.jitter.center.color = 'grey50',
      fancy.variant.boxplot.base_size = 12,
      fancy.variant.boxplot.plot.margin = 1,
      fancy.variant.boxplot.vaf.suffix = '',
      # bell plot parameters
      clone.shape = 'bell',
      bell.event = TRUE,
      bell.event.label.color = 'blue',
      bell.event.label.angle = 60,
      clone.time.step.scale = 1,
      bell.curve.step = 2,
      # node-based consensus tree parameters
      merged.tree.plot = TRUE,
      tree.node.label.split.character = NULL,
      tree.node.shape = 'circle',
      tree.node.size = 30,
      tree.node.text.size = 0.5,
      merged.tree.node.size.scale = 1.25,
      merged.tree.node.text.size.scale = 2.5,
      merged.tree.cell.frac.ci = FALSE,
      # branch-based consensus tree parameters
      merged.tree.clone.as.branch = TRUE,
      mtcab.event.sep.char = ',',
      mtcab.branch.text.size = 1,
      mtcab.branch.width = 0.75,
      mtcab.node.size = 3,
      mtcab.node.label.size = 1,
      mtcab.node.text.size = 1.5,
      # cellular population parameters
      cell.plot = TRUE,
      num.cells = 100,
      cell.border.size = 0.25,
      cell.border.color = 'black',
      clone.grouping = 'horizontal',
      #meta-parameters
      scale.monoclonal.cell.frac = TRUE,
      show.score = FALSE,
      cell.frac.ci = TRUE,
      disable.cell.frac = FALSE,
      # output figure parameters
      #out.dir = basename(cloneResultFile),
      out.dir = ".",
      out.prefix= basename(cloneResultFile),
      out.format = 'pdf',
      overwrite.output = TRUE,
      width = 15,
      height = 5,
      # vector of width scales for each panel from left to right
      panel.widths = c(3, 4, 2, 4, 2)
    )
  )
  #  break;
}

