---
title: "Differential Analysis Report"
author: "Shilin Zhao<br><small>Department of Biostatistics<br>Vanderbilt University School of Medicine</small>"
date: "<small>`r Sys.Date()`</small>"
output:
  html_document:
    toc: yes
    toc_depth: 3
    number_sections: false
    toc_float: 
      collapsed: true
    # code_folding: hide
    # theme: cerulean
    # keep_md: true
description: "Differential Analysis Report"
---

<style type="text/css">
.main-container {
  max-width: 90%;
  margin-left: auto;
  margin-right: auto;
}
</style>


```{r setup, include=FALSE}
library(knitr)

options(width = 3000,warning=FALSE)

```


```{r child = 'reportFunctions.Rmd',eval=file.exists("reportFunctions.Rmd")}
```

  
```{r loadData, include=FALSE}


knitr::opts_chunk$set(fig.width=7, fig.height=6, out.width=800, out.height=600)

##Test folder
#setwd("/scratch/cqs/zhaos/AnthonyDaniels/20190903_proteomicsTumorNormalPair_Limma/report/result/")

files<-read.table("fileList1.txt", header=FALSE, as.is=TRUE)
#files<-read.table("/scratch/cqs/zhaos/AnthonyDaniels/20190903_proteomicsTumorNormalPair_Limma/webgestaltReportTest/result/fileList1.txt", header=FALSE, as.is=TRUE)
#rownames(files)<-files$V2


```



```{r child = 'DiffGeneReport.Rmd',eval=file.exists("DiffGeneReport.Rmd")}
```



# Funcional enrichment analysis \n <br> List of the top five significantly enriched elements

```{r,include=FALSE,results='hide',message=TRUE,eval=TRUE}
reportModules=c("webgestaltReport.Rmd","GSEAShortReport.Rmd","KEGGprofileReport.Rmd")
out = NULL

for (i in 1:length(reportModules)) {
  rmdFile=reportModules[i]
  if (file.exists(rmdFile)) {
    message(paste0("Working in ",rmdFile))
    out = c(out, knit_child(rmdFile))
  } else {
    warning(paste0("File ",rmdFile," defined in reportModules but doesn't exist."))
  }
  
}


```

`r if (exists("out") && !is.null(out)) paste(knit(text = out), collapse = '\n')`



