---
title: "GSEA Report"
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output: 
  rmdformats::readthedown:
    toc_depth: 2
    number_sections: false
---

```{css, echo=FALSE}
#content{
    max-width:1920px;
}
```

<style type="text/css">
    div.datatables { height: auto !important;}
</style>

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(kableExtra)
knitr::opts_chunk$set(echo=FALSE,  message=FALSE, warning=FALSE, results = 'asis', fig.width=7, fig.height = 7,tidy = TRUE, tidy.opts = list(comment = FALSE))
```
```{r,echo=FALSE,warning=FALSE,message=FALSE}
library(ggplot2)
library(RColorBrewer)
library(reshape2)
library(DT)
library(RCurl)
library(htmltools)
library(knitr)
library(kableExtra)

source('reportFunctions.R')
source('Pipeline.R')

files<-read.csv("gsea_files.csv", as.is=TRUE)

resFile<-"sub.Rmd"
figureRmd<-function(files){
  result<-""
  comparisons = unique(files$comparison)
  comparison<-comparisons[1]
  for(comparison in comparisons){
    result<-paste0(result, paste0("\n\n# ", comparison, "\n\n"))

    comp_files<-files[files$comparison==comparison,,drop=FALSE]

    categories = unique(comp_files$category)
    category=categories[1]
    for(category in categories){
      result<-paste0(result, paste0("\n\n## ", category, "\n\n"))

      cat_files<-comp_files[comp_files$category == category,,drop=F]
      file_map<-split(cat_files$file_path, cat_files$file_key)

      if(!is.null(file_map$pos_file)){
        result<-paste0(result, paste0("\n\n### Positive-regulated\n\n"))
        result<-paste0(result, getTable(file_map$pos_file))
      }

      if(!is.null(file_map$neg_file)){
        result<-paste0(result, paste0("\n\n### negative-regulated\n\n"))
        result<-paste0(result, getTable(file_map$neg_file))
      }

      if(!is.null(file_map$enriched_file)){
        result<-paste0(result, paste0("\n\n### Enrichment\n\n"))
        result<-paste0(result, getTable(file_map$enriched_file))
        result<-paste0(result, getFigure(file_map$enriched_png))
      }
    }
  }
  return(result)
}
cat(figureRmd(files), file=resFile)
```

```{r, child=resFile} 
```
