```{r}
if(!exists('title_prefix')){
  title_prefix=""
}
```

## `r title_prefix` Pathway Analysis

```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
load_install<-function(library_name, library_sources=library_name){
  if(!require(library_name, character.only = T)){
    BiocManager::install(library_sources, ask=FALSE)
  }
  library(library_name, character.only = T)
}

load_install("org.Hs.eg.db")
load_install("ComplexHeatmap")
load_install("clusterProfiler")
load_install("ReactomePA")

if(!exists("lib_folder")){
  lib_folder="https://raw.githubusercontent.com/shengqh/ngsperl/master/lib"
}
source(paste0(lib_folder, "/CQS/reportFunctions.R"))
source(paste0(lib_folder, "/Report/enrichmentByClusterProfiler.R"))
```

```{r}
#varaables defined from list
if (exists("reportParametersList") && "pathway_parameter_list" %in% names(reportParametersList)) {
  for (varName in names(reportParametersList$pathway_parameter_list)) {
    assign(varName,reportParametersList$pathway_parameter_list[[varName]])
  }
  
  background_genes=reportParametersList$background_genes
  target_genes=reportParametersList$target_genes
  prefix=reportParametersList$prefix
}
```

There are `r length(target_genes)` target genes.

```{r}
#make sure all required variables are defined
stopifnot(exists("prefix"))

#target_genes is a list of genes that will be the testing set that we will look at where the background_genes is the full list of genes that were tested to get the target genes.
stopifnot(exists("target_genes"))
stopifnot(exists("background_genes"))
stopifnot(exists("organism"))
stopifnot(exists("OrgDb"))

#Options 
stopifnot(exists("pathway_analysis_sets"))
stopifnot(exists("fromType"))
stopifnot(exists("pathway_toType"))

has_background_genes = !all(is.null(background_genes))
```

```{r, error=FALSE, warning=FALSE, message=FALSE, results='asis'}
if(!exists("pathway_width")){
  pathway_width=6
}
if(!exists("pathway_height")){
  pathway_height=4
}

res<-do_pathway(genes=target_genes,
                universe=background_genes,
                modules=pathway_analysis_sets,
                organism=organism,
                fromType=fromType,
                toType=pathway_toType,
                OrgDb=OrgDb)
saveRDS(res, paste0(prefix,"_pathway.rds"))     
```

```{r}
dataForPlotList=res$dataForPlot

rmd=""
pname=pathway_analysis_sets[1]
for(pname in pathway_analysis_sets){
  lst=show_pathway(
    dataForPlotList=dataForPlotList,
    pname=pname,
    prefix=prefix, 
    pathway_width=pathway_width, 
    pathway_height=pathway_height,
    plot_type="dot")

  rmd=paste0(rmd, "\n\n### ", pname, "\n\n")
  if(nrow(lst$res_tbl) == 0){
    rmd=paste0(rmd, "No enriched pathways found.\n\n")
  }else{
    rmd=paste0(rmd, getPagedTable(lst$csv))

    if(is.null(lst$png)){
      rmd=paste0(rmd, "With only ", nrow(lst$res_tbl), " significant pathway, no figure generated.\n\n")
    }else{
      rmd=paste0(rmd, getFigure_width_height(lst$png, fig.width=pathway_width, fig.height=pathway_height))
    }
  }
}
writeLines(rmd, paste0(prefix,"_pathway.rmd"))
```

```{r child=paste0(prefix,"_pathway.rmd")}
```
