---
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output: 
  rmdformats::readthedown:
    toc_depth: 4
    code_folding: hide
    number_sections: yes
---

```{css, echo=FALSE}
#content{
    max-width:1920px;
}
```

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo=FALSE,  
                      message=FALSE, 
                      warning=FALSE, 
                      results = 'asis', 
                      fig.width=7, 
                      fig.height = 7,
                      tidy = TRUE, 
                      tidy.opts = list(comment = FALSE))
```

```{css, echo=FALSE}
#content{
    max-width:1920px;
}

.main-container {
  max-width: 1920px !important;
  margin-left: auto;
  margin-right: auto;
}
```

```{r data, echo = FALSE}
source("reportFunctions.R")

options(future.globals.maxSize = 600000 * 1024^2)
options(future.seed = TRUE)

myoptions<-read_file_map("fileList2.txt", do_unlist=FALSE)
email=myoptions$email
affiliation=get_affiliation(myoptions)
task_name=myoptions$task_name
```

---
title: "NuXL Peptide Reports - `r task_name`"
author:
- name: `r email`
  affiliation: `r affiliation`
---

## QC reports {.tabset}

```{r}
file_map=read_file_map('fileList1.txt')

peptides=NULL
for(fname in names(file_map)){
  cur_peptides=fread(file_map[fname], data.table=FALSE) |>
    dplyr::select(-target_decoy, -NuXL_isXL, -fragment_annotation)
  if(nrow(cur_peptides) > 0){
    cur_peptides$Sample = fname
    peptides = rbind(peptides, cur_peptides)
  }
}
print_table(peptides, byDT=TRUE, row.names=FALSE)
```

