---
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmdformats::readthedown:
    toc_depth: 3
    code_folding: hide
    number_sections: true
---

```{css, echo=FALSE}
#content{
    max-width:1920px;
}
```

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
library(Hmisc)
require(arsenal)
library(tibble)
library(tools)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(ComplexHeatmap)
library(reshape2)
library(readxl)
library(openxlsx)
library(ggvenn)

knitr::opts_chunk$set(
  echo=TRUE, 
  include=TRUE, 
  warning=FALSE, 
  message=FALSE, 
  results="asis"
)
if(0){
  setwd('/nobackup/vickers_lab/test/20240207_lipidomics_20231207/preprocess/result')
}
```

```{r}
source('reportFunctions.R')
source('lipidomics_func.R')
source('countTableVisFunctions.R')

myoptions=read_file_map("fileList1.preprocess.txt", do_unlist=FALSE)
email=myoptions$email
affiliation=myoptions$affiliation
task_name=myoptions$task_name
anno_file=myoptions$nomenclature_file
combine_by=myoptions$combine_by

if(!combine_by %in% c("SUM", "HIGHEST")){
  stop(paste0("Unknown combine_by value, ", combine_by, ". It should be HIGHEST or SUM."))
}
```

---
title: Lipidomics Data Preprocessing of Project `r gsub(":", " ", task_name)`
author:
- name: `r email`
  affiliation: `r affiliation`
---

```{r}
data_files=read_file_map("fileList2.preprocess.txt", do_unlist=FALSE)
pos_file=data_files$POS
neg_file=data_files$NEG

cur_folder = getwd()
preprocess_folder = paste0(cur_folder, "/preprocess_result/")
if(!dir.exists(preprocess_folder)){
  dir.create(preprocess_folder)
}

result_prefix=paste0(preprocess_folder, task_name)
annotated_prefix=paste0(result_prefix, '.annotated')
```

# MD5 of files

```{r}
md5_tbl=rbind(
  data.frame("file"=anno_file, "md5"=""),
  c(pos_file,""),
  c(neg_file,"")
)

for(i in 1:nrow(md5_tbl)){
  md5_tbl$md5[i] = check_md5(md5_tbl$file[i], expect_md5="", return_md5=TRUE)
}

print_table(md5_tbl, row.names=F)
```

```{r child="lipidomics_preprocessing.Rmd"}
```

# Save the session information

```{r}
writeLines(capture.output(sessionInfo()), 'sessionInfo.txt')
```
