---
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output: 
  rmdformats::readthedown:
    toc_depth: 4
    code_folding: hide
---

```{css, echo=FALSE}
#content{
    max-width:1920px;
}
```

```{r setup, echo = F, message=FALSE}
knitr::opts_chunk$set(
  echo=FALSE,  
  message=FALSE, 
  warning=FALSE, 
  results = 'asis', 
  fig.width=7, 
  fig.height = 7
)
```

```{r}
library(ggsci)
library(ggplot2)
library(pheatmap)
library(limma)
library(DT)
library(reshape2)
library(data.table)
library(htmltools)
library(randomcoloR)

source('reportFunctions.R')
source('lipidomics_func.R')
source('countTableVisFunctions.R')

myoptions=read_file_map("fileList1.qc.txt", do_unlist=FALSE)
email=myoptions$email
task_name=myoptions$task_name
affiliation=myoptions$affiliation

if(!"remove_sample_pattern" %in% names(myoptions)){
  myoptions$remove_sample_pattern <- ""
}
if(!"remove_sample_description" %in% names(myoptions)){
  myoptions$remove_sample_description <- ""
}
```

---
title: Lipidomics QC of Project `r gsub(":", " ", task_name)`
author:
- name: `r email`
  affiliation: `r affiliation`
---

# Input files

## Metadata 

```{r}
meta_file <- fread("fileList3.qc.txt", header=F, data.table = F)$V1[1]
```

Read `r meta_file` file

```{r}
meta <- fread(meta_file, data.table = F)
sample_group_map=unlist(split(meta$Class, meta$Class_Sample))
datatable(meta, rownames = F)
```

## Data files

```{r}
list_file <- fread("fileList2.qc.txt", header=F, data.table = F)$V1[1]
```

Read `r list_file` file

```{r}
files <- fread(list_file, header = T, data.table = F)
datatable(files, rownames = F)
```

Read data files, rename Sample with Class_Sample.

```{r}
read_files<-function(files, file_column){
  files_list <- list()
  for (i in 1:nrow(files)){
    df <- read.csv(files[i,file_column], row.names=1)
    stopifnot(all(colnames(df) == meta$Sample))
    colnames(df) <- meta$Class_Sample
    files_list[[i]]=df
  }
  names(files_list) <- files$Name
  return(files_list)
}

raw_files_list <- read_files(files, "RawFile")
log_files_list <- read_files(files, "LogFile")
```

```{r}
remove_samples<-function(files_list, pattern){
  result <- lapply(files_list, function(x){
    y <- x[, -grep(pattern, colnames(x))]
    return(y)
  })
  return(result)
}

if(myoptions$remove_sample_pattern != ""){
  cat("\n# Remove samples\n\n")
  cat(myoptions$remove_sample_description, "\n\n")

  raw_files_list_sel <- remove_samples(files_list=raw_files_list, pattern=myoptions$remove_sample_pattern)
  log_files_list_sel <- remove_samples(files_list=log_files_list, pattern=myoptions$remove_sample_pattern)

  meta_sel <- meta[-grep(myoptions$remove_sample_pattern, meta$Class_Sample),]
  datatable(meta_sel, rownames = F)
}else{
  raw_files_list_sel <- raw_files_list
  log_files_list_sel <- log_files_list

  meta_sel=meta
}
rm(raw_files_list, log_files_list, meta)
```

```{r}
melt_samples<-function(files_list){
  files_list_melt <- lapply(files_list, function(x){
    x$Feature<-rownames(x)
    #somehow melt is not compatible with data.table, so use read.csv to read data in previous trunk.
    a <- reshape2::melt(x, id.vars="Feature")
    b <- cbind(a, Group = unname(unlist(sample_group_map[as.character(a$variable)])))
    return(b)
  })
  return(files_list_melt)
}

raw_files_list_melt <- melt_samples(raw_files_list_sel)
log_files_list_melt <- melt_samples(log_files_list_sel)
```

```{r}
box_width=6
box_height=5

draw_boxplot <- function(data, category, prefix){
  p <- ggplot(data, aes(x=variable, y=value, fill = Group)) + 
    geom_boxplot() +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5)) +
    labs(x = "", y = "Log(concentration)", title=category)

  if(length(unique(data$Group)) < 10){
    p <- p + scale_color_brewer(palette = "Set1")
  }

  png_file = paste0(prefix, ".boxplot.png")
  ggsave(png_file, plot = p, width = box_width, height = box_height, dpi = 300, units = "in", bg="white")
  return(png_file)
}

result = "\n# Boxplots\n\n"
for (i in 1:length(log_files_list_melt)){
  category = names(log_files_list_melt)[i]
  result = paste0(result, "\n\n## ", category, "\n")
  png_file = draw_boxplot(log_files_list_melt[[i]], category, prefix=paste0(task_name, ".", category))
  result = paste0(result, getFigure_width_height(png_file, fig.width=box_width, fig.height=box_height))
}

```

```{r}
pca_width=6
pca_height=5

draw_pca <- function(data, groups, category, prefix){
  data_t <- t(data)
  pca <- prcomp(data_t)
  pcadata<-data.frame(pca$x)
  sum_pca <- summary(pca)$importance
  pcadata$groups <- groups
  
  p <- ggplot(pcadata, aes(x=PC1, y=PC2, color=groups)) + #, label = rownames(pcadata))) 
    geom_point(size = 4) + 
    theme_classic() +
    labs(x=paste0("PCA1 (", round(sum_pca[2,1] * 100, digits = 1), "%)"),
         y=paste0("PCA2 (", round(sum_pca[2,2] * 100, digits = 1), "%)"),
         title=category) +
    theme(axis.text = element_text(size = 16), 
          axis.title = element_text(size=18, face = "bold"), 
          legend.text=element_text(size=16), 
          legend.title= element_blank(),
          plot.title = element_text(hjust = 0.5),
          aspect.ratio=1)
  
  if(length(unique(groups)) < 10){
    p <- p + scale_color_brewer(palette = "Set1")
  }

  png_file = paste0(prefix, ".pca.png")
  ggsave(png_file, plot = p, width = pca_width, height = pca_height, dpi = 300, units = "in", bg="white")
  return(png_file)
}

result = paste0(result, "\n# PCA\n\n")
for (i in 1:length(log_files_list_sel)){
  category = names(log_files_list_sel)[i]
  result = paste0(result, "\n\n## ", category, "\n")
  png_file = draw_pca(data=log_files_list_sel[[i]], groups=meta_sel$Class, category=category, prefix=paste0(task_name, ".", category))
  result = paste0(result, getFigure_width_height(png_file, fig.width=pca_width, fig.height=pca_height))
}
```

```{r}
heatmap_width=7
heatmap_heights=c(5, 4.5, 4, 3)

draw_pheatmap <- function(data_df, groups, annotation_colors, category, prefix, heatmap_width, heatmap_height){
  show_rownames = ifelse(nrow(data_df) <= 30, TRUE, FALSE)
  cellheight = ifelse(nrow(data_df) <= 30, 8, 2)
  png_file = paste0(prefix, ".heatmap.png")
  pheatmap( data_df, 
            main = category,
            scale = "row", 
            show_rownames = show_rownames, 
            annotation_col = groups, 
            annotation_colors = annotation_colors, 
            annotation_legend = F, 
            annotation_names_col = F, 
            border_color = NA,  
            fontsize = 7, 
            cellheight = cellheight, 
            cluster_cols = T,
            filename=png_file,
            width=heatmap_width,
            height=heatmap_height)
  #g <- p1[[4]]
  #ggsave(png_file, g, width = heatmap_width, height = heatmap_height, dpi = 300, units = "in", bg="white")
  return(png_file)
}

groups <- data.frame(row.names = meta_sel$Class_Sample, groups = meta_sel$Class)

group_names = unique(meta_sel$Class)
groups_colors <- distinctColorPalette(length(group_names))
names(groups_colors) <- group_names

annotation_colors = list(groups = groups_colors)

result = paste0(result, "\n# Heatmap\n\n")
for (i in 1:length(log_files_list_sel)){
  category = names(log_files_list_sel)[i]
  result = paste0(result, "\n\n## ", category, "\n")

  data_df = log_files_list_sel[[i]]
  heatmap_height = heatmap_heights[i]

  png_file = draw_pheatmap(data_df = data_df, 
    groups = groups, 
    annotation_colors = annotation_colors, 
    category=category, 
    prefix=paste0(task_name, ".", category),
    heatmap_width=heatmap_width,
    heatmap_height=heatmap_height)

  if(category == "Species"){
    result = paste0(result, "\n\nSpecies heatmap file=", png_file, "\n\n")
  }

  result = paste0(result, getFigure_width_height(png_file, fig.width=heatmap_width, fig.height=heatmap_height))
}
```

```{r}
stacked_width=7
stacked_height=4

select_top_n <- function(data, n, max_n){
  if(nrow(data) <= max_n){
    return(rownames(data))
  }
 
  rn <- row.names(data)
  f <- function(x) tail(rn[order(x)], n = n)
  top_names = unique(unlist(as.list(sapply(data, f))))

  if(length(top_names) > max_n){
    top_data=data[top_names,]
    top_ranked=tail(sort(apply(top_data, 1, sum)), 10)
    top_names=names(top_ranked)
  }

  return(top_names)
}

draw_stacked <- function(data, category, prefix){
  p <- ggplot(data, aes(x=variable, y=value, fill = Feature)) + 
    geom_bar(position="stack", stat="identity") +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5)) +
    labs(x = "", y = "Concentration", title=category)
  png_file = paste0(prefix, ".bar_count.png")
  ggsave(png_file, plot = p, width = stacked_width, height = stacked_height, dpi = 300, units = "in", bg="white")
  return(png_file)
}

draw_stacked_per <- function(data, category, prefix){
  p <- ggplot(data, aes(x=variable, y=value, fill = Feature)) + 
    geom_bar(position="fill", stat="identity") +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5)) +
    labs(x = "", y = "Percentage", title=category)
  png_file = paste0(prefix, ".bar_perc.png")
  ggsave(png_file, plot = p, width = stacked_width, height = stacked_height, dpi = 300, units = "in", bg="white")
  return(png_file)
}

datafiles=data.frame(category=names(raw_files_list_melt), file="")

result = paste0(result, "\n# Stacked barplot\n\n")
i=1
for (i in 1:length(raw_files_list_melt)){
  category = names(raw_files_list_melt)[i]
  result = paste0(result, "\n\n## ", category, "\n")

  top_f_genes = select_top_n(data=raw_files_list_sel[[i]], n=5, max_n=10)

  data=raw_files_list_melt[[i]]
  top_data=data[data$Feature %in% top_f_genes,]

  other_data=data[!data$Feature %in% top_f_genes,]
  if(nrow(other_data) > 0){
    other_df = aggregate(other_data$value, by=list(variable=other_data$variable, Group=other_data$Group), FUN=sum)
    other_df$Feature = "Other"
    colnames(other_df) = c("variable", "Group", "value", "Feature")
    other_df=other_df[,colnames(top_data)]
    cur_data=rbind(top_data, other_df)
    cur_data$Feature=factor(cur_data$Feature, levels=c("Other", top_f_genes))
  }else{
    #cat("No other data for ", category, "\n")
    cur_data=top_data
    cur_data$Feature=factor(cur_data$Feature, levels=top_f_genes)
  }
  category_csv = paste0(task_name, ".", category, ".csv")
  write.csv(cur_data, category_csv, row.names=FALSE)
  datafiles$file[i]=normalizePath(category_csv)

  png_file = draw_stacked(cur_data, category=category, prefix=paste0(task_name, ".", category))
  result = paste0(result, getFigure_width_height(png_file, fig.width=stacked_width, fig.height=stacked_height))

  png_file = draw_stacked_per(cur_data, category=category, prefix=paste0(task_name, ".", category))
  result = paste0(result, getFigure_width_height(png_file, fig.width=stacked_width, fig.height=stacked_height))
}
write.table(datafiles, paste0(task_name, ".files.txt"), row.names=FALSE, sep="\t", quote=FALSE)
```

```{r}
qc_rmd="qc.rmd"
writeLines(result, qc_rmd)
```

```{r child=qc_rmd}
```
